### ISSUE TITLE
feat: Badge copmponent

### ISSUE THREAD

**Issue by dodo849** [dodo849/DesignSystemBookApp#6]
## 🚀 Highlights

Write the main purpose of the issue.
- Bedge 컴포넌트 추가하기

## 📌 Tasks

List the features you plan to develop.
- [ ] Bedge Theme 생성
- [ ] Bedge Theme UIKit coponent 생성
- [ ]  Bedge Theme SwiftUI coponent 생성

## 📝 Details

Write the details about the feature.

- x

## 📚 Remarks

- x
